name: Deploy API e Frontend

on:
  push:
    tags:
      - 'v*' 

jobs:
  # ==========================================
  # 1. JOB DE DEPLOY DA API (PHP)
  # ==========================================
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout do c贸digo
        uses: actions/checkout@v3

      - name: 锔 Criar arquivo .env de Produ莽茫o da API
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST_BFF }}" >> public/api/.env
          echo "DB_PORT=3306" >> public/api/.env
          echo "DB_NAME=${{ secrets.DB_NAME_PROD }}" >> public/api/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> public/api/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> public/api/.env
          echo "APP_ENV=production" >> public/api/.env

      - name: Ч Limpar arquivos inseguros
        run: rm -f public/api/info.php

      - name:  Deploy da API via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME_BFF }}
          password: ${{ secrets.FTP_PASSWORD_BFF }}
          port: 65002
          source: "public/api/*"
          target: "./"
          strip_components: 2 # Remove os dois primeiros n铆veis de diret贸rios (public/api) para evitar criar subpastas indesejadas

  # ==========================================
  # 2. JOB DE DEPLOY DO FRONTEND (REACT/VITE)
  # ==========================================
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout do c贸digo
        uses: actions/checkout@v3

      - name:  Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 锔 Criar .env do React e Gerar Build
        run: |
          cd public/web
          # Usando um 煤nico '>' para CRIAR o arquivo do zero usando o Secret do GitHub
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_URL }}" > .env.production
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env.production
          rm -f package-lock.json
          npm install
          npm run build

      - name:  Deploy do Frontend via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME_GHZLIFE }}
          password: ${{ secrets.FTP_PASSWORD_GHZLIFE }}
          port: 65002
          source: "public/web/dist/*"
          target: "./"
          strip_components: 2 # Remove os dois primeiros n铆veis de diret贸rios (public/web/dist) para evitar criar subpastas indesejadas